[build]
  publish = "public" # Directory where your site files are located
  functions = "netlify/functions" # Directory for Netlify Functions if applicable

[[redirects]]
  from = "/success.html"
  to = "/success.html"
  status = 200